import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '@/components/AppHeader'; import { bibleRepository } from '@/repositories/BibleRepository'; import { userBibleStorage } from '@/storage/UserBibleStorage'; import { colors, radius, sizes, spacing, typography } from '@/theme/tokens';
export default function Chapters(){const {book:bookId}=useLocalSearchParams<{book:string}>();const book=bibleRepository.getBook(bookId);const [loadedThrough,setLoadedThrough]=useState(1);const chapters=useMemo(()=>book?Array.from({length:loadedThrough},(_,index)=>({number:index+1,verses:bibleRepository.getChapter(book.id,index+1)})):[],[book,loadedThrough]);useEffect(()=>{if(book&&chapters[0]?.verses.length)void userBibleStorage.recordReading({versionId:book.versionId,bookId:book.id,chapter:1});},[book?.id]);if(!book)return <SafeAreaView style={styles.safe}><AppHeader title="Livro indisponível" back /><Text style={styles.message}>Não encontramos esse livro.</Text></SafeAreaView>;
 const header=<><AppHeader title={book.name} subtitle="Escolha um capítulo ou comece a ler" back/><View style={styles.grid}>{Array.from({length:book.chapterCount},(_,index)=>index+1).map(chapter=><Pressable accessibilityRole="button" key={chapter} style={styles.chapter} onPress={()=>router.push({pathname:'/bible/[book]/[chapter]',params:{book:book.id,chapter:String(chapter)}})}><Text style={styles.number}>{chapter}</Text></Pressable>)}</View><Text style={styles.read}>Ler {book.name}</Text></>;
 return <SafeAreaView style={styles.safe} edges={['top','left','right']}><FlatList contentContainerStyle={styles.content} data={chapters} keyExtractor={item=>String(item.number)} ListHeaderComponent={header} onEndReached={()=>setLoadedThrough(current=>Math.min(current+1,book.chapterCount))} onEndReachedThreshold={0.6} renderItem={({item})=><View style={styles.section}><Text style={styles.heading}>{book.name} {item.number}</Text>{item.verses.map(verse=><Text key={verse.id} style={styles.verse}><Text style={styles.verseNumber}>{verse.verse} </Text>{verse.text}</Text>)}</View>}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{width:'100%',maxWidth:sizes.contentMax,alignSelf:'center',padding:spacing.xl,paddingBottom:spacing.huge},grid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},chapter:{width:48,height:48,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface,borderRadius:radius.md},number:{...typography.body,color:colors.ink,fontWeight:'600'},read:{...typography.heading,color:colors.ink,marginTop:spacing.xxl},section:{marginTop:spacing.xl},heading:{...typography.heading,color:colors.ink,marginBottom:spacing.md},verse:{fontSize:19,lineHeight:31,color:colors.ink,marginBottom:spacing.xs},verseNumber:{...typography.caption,color:colors.gold},unavailable:{...typography.body,color:colors.muted},message:{...typography.body,color:colors.muted,padding:spacing.xl}});
