import { developmentBibleData } from '@/data/developmentBibleData';
import { BibleBook, BibleSearchResult, BibleVerse, BibleVersion, ChapterLocation, Testament } from '@/models/bible';
import { normalizeSearch, parseReference } from '@/search/referenceParser';
const legacyBooks: Record<string,string>={ 'book-gen':'GEN','book-ps':'PSA','book-mt':'MAT','book-jn':'JHN','book-act':'ACT' };
class BibleRepository {
 private books=[...developmentBibleData.books].sort((a,b)=>a.order-b.order); private bookById=new Map(this.books.map(book=>[book.id,book])); private versesByChapter=new Map<string,BibleVerse[]>(); private verseById=new Map<string,BibleVerse>();
 constructor(){ for(const verse of developmentBibleData.verses){this.versesByChapter.set(`${verse.bookId}:${verse.chapter}`,[...(this.versesByChapter.get(`${verse.bookId}:${verse.chapter}`)??[]),verse]);this.verseById.set(verse.id,verse);} }
 getVersions():BibleVersion[]{return developmentBibleData.versions;} getDefaultVersion(){return developmentBibleData.versions[0];} getBooks(versionId:string){return this.books.filter(book=>book.versionId===versionId);} getBooksByTestament(versionId:string,testament:Testament){return this.getBooks(versionId).filter(book=>book.testament===testament);} getBook(bookId:string){return this.bookById.get(legacyBooks[bookId]??bookId);} getChapter(bookId:string,chapter:number){return this.versesByChapter.get(`${bookId}:${chapter}`)??[];} getVerse(verseId:string){const direct=this.verseById.get(verseId);if(direct)return direct;const match=verseId.match(/^dev-pt-001:(book-[a-z]+):(\d+):(\d+)$/);if(!match)return;return this.verseById.get(`dev-pt-001-${legacyBooks[match[1]]}-${match[2]}-${match[3]}`);} getChapterCount(bookId:string){return this.getBook(bookId)?.chapterCount??0;}
 private adjacent(bookId:string,chapter:number,direction:-1|1):ChapterLocation|undefined{const index=this.books.findIndex(book=>book.id===bookId);if(index<0)return; if(direction<0&&chapter>1)return{bookId,chapter:chapter-1};if(direction>0&&chapter<this.books[index].chapterCount)return{bookId,chapter:chapter+1};const next=this.books[index+direction];return next?{bookId:next.id,chapter:direction>0?1:next.chapterCount}:undefined;} getPreviousChapter(bookId:string,chapter:number){return this.adjacent(bookId,chapter,-1);} getNextChapter(bookId:string,chapter:number){return this.adjacent(bookId,chapter,1);} formatReference(verse:BibleVerse){return `${this.getBook(verse.bookId)?.name??'Livro'} ${verse.chapter}:${verse.verse}`;}
 search(rawQuery:string,versionId=this.getDefaultVersion().id):BibleSearchResult[]{const query=normalizeSearch(rawQuery);if(query.length<2)return[];const books=this.getBooks(versionId);const reference=parseReference(rawQuery,books);const prioritized:BibleSearchResult[]=[];if(reference){if(reference.chapter===undefined)prioritized.push({type:'book',book:reference.book});else if(reference.verse===undefined)prioritized.push({type:'chapter',book:reference.book,chapter:reference.chapter});else{const verse=this.getChapter(reference.book.id,reference.chapter).find(item=>item.verse===reference.verse);if(verse)prioritized.push({type:'verse',book:reference.book,verse});}}
 const bookResults: BibleSearchResult[]=books.filter(book=>normalizeSearch(book.name).includes(query)||normalizeSearch(book.abbreviation)===query).map(book=>({type:'book',book}));const verseResults: BibleSearchResult[]=developmentBibleData.verses.filter(verse=>verse.versionId===versionId&&normalizeSearch(verse.text).includes(query)).slice(0,30).map(verse=>({type:'verse',book:this.bookById.get(verse.bookId)!,verse}));return [...prioritized,...bookResults,...verseResults].filter((result,index,all)=>all.findIndex(candidate=>JSON.stringify(candidate)===JSON.stringify(result))===index).slice(0,30);}
}
export const bibleRepository=new BibleRepository();
