import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppHeader } from '@/components/AppHeader';
import { Screen } from '@/components/Screen';
import { SectionHeader } from '@/components/SectionHeader';
import { BibleSearchResult } from '@/models/bible';
import { bibleRepository } from '@/repositories/BibleRepository';
import { colors, radius, spacing, typography } from '@/theme/tokens';
export default function Bible() { const version = bibleRepository.getDefaultVersion(); const [query, setQuery] = useState(''); const [debounced, setDebounced] = useState(''); useEffect(() => { const timer = setTimeout(() => setDebounced(query), 250); return () => clearTimeout(timer); }, [query]); const results = useMemo(() => bibleRepository.search(debounced), [debounced]); const old = bibleRepository.getBooksByTestament(version.id, 'old'); const recent = bibleRepository.getBooksByTestament(version.id, 'new'); const openResult = (result: BibleSearchResult) => { if (result.type === 'book') router.push({ pathname: '/bible/[book]', params: { book: result.book.id } }); else { const chapter = result.type === 'chapter' ? result.chapter : result.verse.chapter; router.push({ pathname: '/bible/[book]/[chapter]', params: { book: result.book.id, chapter: String(chapter), ...(result.type === 'verse' ? { verse: result.verse.id } : {}) } }); } }; const renderBook = (book: (typeof old)[number]) => <Pressable accessibilityRole="button" accessibilityLabel={`${book.name}, ${book.chapterCount} capítulos`} key={book.id} onPress={() => router.push({ pathname: '/bible/[book]', params: { book: book.id } })} style={styles.row}><View style={styles.grow}><Text style={styles.name}>{book.name}</Text><Text style={styles.count}>{book.chapterCount} capítulos</Text></View><Feather name="chevron-right" size={19} color={colors.muted} /></Pressable>;
return <Screen><AppHeader title="Bíblia" /><View style={styles.version}><Feather name="book-open" size={15} color={colors.gold} /><Text style={styles.versionText}>{version.name}</Text></View><View style={styles.search}><Feather name="search" size={19} color={colors.muted} /><TextInput accessibilityLabel="Buscar na Bíblia" value={query} onChangeText={setQuery} placeholder="Buscar livro, capítulo ou versículo" placeholderTextColor={colors.muted} style={styles.input} /></View>{debounced.trim().length >= 2 ? <View><SectionHeader title="Resultados" />{results.length ? results.map((result, index) => { const key = result.type === 'book' ? result.book.id : result.type === 'chapter' ? `${result.book.id}:${result.chapter}` : result.verse.id; const title = result.type === 'book' ? result.book.name : result.type === 'chapter' ? `${result.book.name} ${result.chapter}` : bibleRepository.formatReference(result.verse); const detail = result.type === 'book' ? `${result.book.chapterCount} capítulos` : result.type === 'verse' ? result.verse.text : 'Abrir capítulo'; return <Pressable key={`${key}:${index}`} onPress={() => openResult(result)} style={styles.result}><Text style={styles.name}>{title}</Text><Text numberOfLines={2} style={styles.count}>{detail}</Text></Pressable>; }) : <Text style={styles.empty}>Nenhum resultado encontrado.</Text>}</View> : <><SectionHeader title="Antigo Testamento" />{old.map(renderBook)}<SectionHeader title="Novo Testamento" />{recent.map(renderBook)}</>}</Screen>; }
const styles = StyleSheet.create({ version: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, marginBottom: spacing.lg }, versionText: { ...typography.caption, color: colors.muted }, search: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md, paddingHorizontal: spacing.lg }, input: { ...typography.body, flex: 1, color: colors.ink }, row: { minHeight: 64, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, grow: { flex: 1 }, name: { ...typography.body, color: colors.ink, fontWeight: '600' }, count: { ...typography.caption, color: colors.muted, marginTop: 2 }, result: { paddingVertical: spacing.lg, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, empty: { ...typography.body, color: colors.muted, paddingVertical: spacing.xl } });
